/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as IndexRouteImport } from './routes/index'

const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facturas': typeof FacturasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facturas': typeof FacturasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facturas': typeof FacturasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/facturas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/facturas'
  id: '__root__' | '/' | '/facturas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacturasRoute: typeof FacturasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacturasRoute: FacturasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
